### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined  when open in chrome

### ISSUE THREAD

**Issue by xZGit** [ng-book/angular2-rxjs-chat#3]
```javascript
TypeError: Cannot read property 'name' of undefined
    at AbstractChangeDetector.ChangeDetector_ChatWindow_comp_0.detectChangesInRecordsInternal (eval at <anonymous> (http://localhost:8080/bundle.js:4509:17), <anonymous>:29:33)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:8080/bundle.js:4820:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/bundle.js:4797:15)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8080/bundle.js:4883:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/bundle.js:4801:15)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8080/bundle.js:4883:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/bundle.js:4801:15)
    at AbstractChangeDetector.detectChanges (http://localhost:8080/bundle.js:4790:74)
    at LifeCycle.tick (http://localhost:8080/bundle.js:26340:35)
    at http://localhost:8080/bundle.js:26316:61
```

as above, I got this error  when run the server step by step... is it a bug or just i miss some step?

**Comment by jashmenn** [comment]
Hmm interesting. I think it might be good for me to get a Docker instance up and running with this app.

**Comment by xZGit** [comment]
Hmm, i support you and my node version is 0.12.2

**Comment by jashmenn** [comment]
Interesting - I'll try and get this running from a clean slate and get back to you. But I'm leaving town tomorrow and won't be back for a few days, so it might be mid-next week before I can give a better answer.

**Comment by xZGit** [comment]
ok  , have a nice trip and waiting for your good news !

**Comment by nadavl** [comment]
Same here... +1

**Comment by jashmenn** [comment]
Okay, I just pushed a commit that pins down the versions of a bunch of npm modules and that fixed the problem. Of course, in the long run we want to make sure TypeScript etc. are all up to date with the latest versions, but for now the set of dependencies in `master` works. So do the following:

```bash
cd angular2-rxjs-chat
rm -rf node_modules
npm install
npm run server
```

**Comment by xZGit** [comment]
It works perfect !!! thank you!
