### ISSUE TITLE
Error webpack-dev-server

### ISSUE THREAD

**Issue by edsonalvesan** [ng-book/angular2-rxjs-chat#5]
Hello, I cloned the repository and follow the installation Arians, but when running npm run server, have the following error:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'run',
1 verbose cli 'server' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose run-script [ 'preserver', 'server', 'postserver' ]
6 info preserver angular2-rxjs-chat@1.0.0
7 info server angular2-rxjs-chat@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular2-rxjs-chat@1.0.0 Failed to exec server script
10 verbose stack Error: angular2-rxjs-chat@1.0.0 server: webpack-dev-server
10 verbose stack Exit status 1
10 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack at EventEmitter.emit (events.js:110:17)
10 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack at ChildProcess.emit (events.js:110:17)
10 verbose stack at maybeClose (child_process.js:1015:16)
10 verbose stack at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid angular2-rxjs-chat@1.0.0
12 verbose cwd C:\xampp\htdocs\Laravel\AngularChat\angular2-rxjs-chat
13 error Windows_NT 6.1.7601
14 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "server"
15 error node v0.12.3
16 error npm v2.9.1
17 error code ELIFECYCLE
18 error angular2-rxjs-chat@1.0.0 server: webpack-dev-server
18 error Exit status 1
19 error Failed at the angular2-rxjs-chat@1.0.0 server script 'webpack-dev-server'.
19 error This is most likely a problem with the angular2-rxjs-chat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error webpack-dev-server
19 error You can get their info via:
19 error npm owner ls angular2-rxjs-chat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by ndcunningham** [comment]
old issue but if anyone has the same upgrade node as per #6
