### ISSUE TITLE
ng e2e fails because it cannot find type definition file for 'jasmine' and 'node'

### ISSUE THREAD

**Issue by khtan** [ng-book/angular2-rxjs-chat#55]
Had to add a line : 
   import {} from 'jasmine'; 
to the file app.e2e-spec.ts.

Have also invoked : npm install at type/node and npm install at type/jasmine'. ( Somehow editor is not displaying the at symbol properly )

However, ng e2e still failed because it could not find type definition file for 'jasmine' and 'node'.

Below is the transcript from the shell:

> ng e2e
** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152 **
(node:15768) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Hash: 576aec247a956d2fa97b
Time: 14135ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 43.7 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 201 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.03 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
[21:47:21] I/update - chromedriver: file exists C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.36.zip
[21:47:21] I/update - chromedriver: unzipping chromedriver_2.36.zip
[21:47:22] I/update - chromedriver: chromedriver_2.36.exe up to date
[21:47:22] I/launcher - Running 1 instances of WebDriver
[21:47:22] I/direct - Using ChromeDriver directly...
[21:47:24] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'jasmine'. (2688)
Cannot find type definition file for 'node'. (2688)
    at getOutput (C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\ts-node\src\index.ts:312:17)
    at C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\jasmine\lib\jasmine.js:93:5
    at Array.forEach (<anonymous>)
    at Jasmine.loadSpecs (C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\jasmine\lib\jasmine.js:92:18)
    at Jasmine.execute (C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\jasmine\lib\jasmine.js:197:8)
    at C:\cprojects\pp\angular\angular2-rxjs-chat\node_modules\protractor\built\frameworks\jasmine.js:132:15
[21:47:24] E/launcher - Process exited with error code 100

**Comment by khtan** [comment]
When I updated ts-node to ~3.3.0 in package.json, ng e2e started working again
